### ISSUE TITLE
CursorsFrameImpl incompatible with new WebLaF

### ISSUE THREAD

**Issue by Sciss** [Sciss/Mellite#106]
In GitLab by @Sciss on Nov 8, 2019, 24:03

With confluent workspaces:

```
java.lang.ClassCastException: class de.sciss.mellite.impl.document.CursorsFrameImpl$CursorView cannot be cast to class javax.swing.tree.TreeNode (de.sciss.mellite.impl.document.CursorsFrameImpl$CursorView is in unnamed module of loader 'app'; javax.swing.tree.TreeNode is in module java.desktop of loader 'bootstrap')
	at com.alee.laf.tree.WebTreeCellRenderer.getTreeCellRendererComponent(WebTreeCellRenderer.java:333)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI$NodeDimensionsHandler.getNodeDimensions(BasicTreeUI.java:3155)
	at java.desktop/javax.swing.tree.AbstractLayoutCache.getNodeDimensions(AbstractLayoutCache.java:493)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.updatePreferredSize(VariableHeightLayoutCache.java:1344)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache.rebuild(VariableHeightLayoutCache.java:723)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache.setModel(VariableHeightLayoutCache.java:111)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI.setModel(BasicTreeUI.java:495)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI$Handler.propertyChange(BasicTreeUI.java:3820)
	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:341)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:333)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:266)
	at java.desktop/java.awt.Component.firePropertyChange(Component.java:8728)
	at java.desktop/javax.swing.JTree.setModel(JTree.java:893)
	at java.desktop/javax.swing.JTree.<init>(JTree.java:679)
	at de.sciss.treetable.j.ui.BasicTreeTableUI$Tree.<init>(BasicTreeTableUI.java:932)
	at de.sciss.treetable.j.ui.BasicTreeTableUI.createTree(BasicTreeTableUI.java:338)
	at de.sciss.treetable.j.ui.BasicTreeTableUI.createAndConfigureTree(BasicTreeTableUI.java:286)
	at de.sciss.treetable.j.ui.BasicTreeTableUI.installComponents(BasicTreeTableUI.java:152)
	at de.sciss.treetable.j.ui.BasicTreeTableUI.installUI(BasicTreeTableUI.java:120)
	at java.desktop/javax.swing.JComponent.setUI(JComponent.java:685)
	at de.sciss.treetable.j.TreeTable.setUI(TreeTable.java:204)
	at de.sciss.treetable.j.TreeTable.updateUI(TreeTable.java:236)
	at de.sciss.treetable.j.TreeTable.<init>(TreeTable.java:124)
	at de.sciss.treetable.TreeTable$$anon$4.<init>(TreeTable.scala:226)
	at de.sciss.treetable.TreeTable.peer$lzycompute(TreeTable.scala:226)
	at de.sciss.treetable.TreeTable.peer(TreeTable.scala:225)
	at de.sciss.treetable.TreeTable.peer(TreeTable.scala:75)
	at scala.swing.UIElement$.scala$swing$UIElement$$cache(UIElement.scala:25)
	at scala.swing.UIElement.$init$(UIElement.scala:83)
	at scala.swing.Component.<init>(Component.scala:45)
	at de.sciss.treetable.TreeTable.<init>(TreeTable.scala:77)
	at de.sciss.treetable.TreeTable.<init>(TreeTable.scala:84)
	at de.sciss.mellite.impl.document.CursorsFrameImpl$ViewImpl.guiInit(CursorsFrameImpl.scala:285)
	at de.sciss.mellite.impl.document.CursorsFrameImpl$ViewImpl.$anonfun$init$1(CursorsFrameImpl.scala:250)
	at de.sciss.lucre.swing.LucreSwing$.$anonfun$handleGUI$2(LucreSwing.scala:45)
	at de.sciss.lucre.swing.LucreSwing$.$anonfun$handleGUI$2$adapted(LucreSwing.scala:43)
```

**Comment by Sciss** [comment]
In GitLab by @Sciss on Nov 8, 2019, 24:08

I guess see https://git.iem.at/sciss/LucreSwing/commit/1e870341e53215f620ec3cfc8becea0b0deebe6c for a recipe

**Comment by Sciss** [comment]
In GitLab by @Sciss on Nov 8, 2019, 24:18

mentioned in commit a72e0b8ec951bcb14927389bf9078656b2d1ba70

**Comment by Sciss** [comment]
In GitLab by @Sciss on Nov 24, 2019, 21:00

closed
