### ISSUE TITLE
Match error in audio cue bounce

### ISSUE THREAD

**Issue by Sciss** [Sciss/Mellite#130]
In GitLab by @Sciss on Dec 8, 2020, 19:09

```
	at de.sciss.mellite.impl.audiocue.AudioCueViewImpl$Impl$actionBounce$.performGUI(AudioCueViewImpl.scala:202)
```
This is for non-normalized mp3 export. The condition `needsFSc && needsPost` does not kick in. Should that be an OR?

**Comment by Sciss** [comment]
In GitLab by @Sciss on Jan 31, 2021, 20:45

mentioned in commit 8519889ba46a266d9f9afdcd1cc5a061f1803169

**Comment by Sciss** [comment]
Damn, this is written in a bad way. 

```
Exception in thread "AWT-EventQueue-0" java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:627)
	at scala.None$.get(Option.scala:626)
	at de.sciss.mellite.impl.audiocue.AudioCueViewImpl$Impl$actionBounce$$anon$2.<init>(AudioCueViewImpl.scala:281)
	at de.sciss.mellite.impl.audiocue.AudioCueViewImpl$Impl$actionBounce$.performGUI(AudioCueViewImpl.scala:261)
```
this is with AIFF immediate, selection.
