### ISSUE TITLE
Create AudioCue - problems with certain path characters, [, ]

### ISSUE THREAD

**Issue by Sciss** [Sciss/Mellite#144]
Seems some characters would have to be escaped/unescaped, e.g. brackets:

```
Illegal character in path at index 34: file:/data/projects/Aleatorium/tmp[1]/
  at java.base/java.net.URI$Parser.fail(URI.java:2913)
  ...
  at de.sciss.asyncfile.Ops$URIOps$.parentOption$extension(Ops.scala:54)
```

**Comment by Sciss** [comment]
E.g. `new java.io.File("/data/projects/Aleatorium/tmp[1]/impact1.aif").toURI` gives `file:/data/projects/Aleatorium/tmp%5B1%5D/impact1.aif`. So we need to check to re-escape characters whenever a URI is constructed, I guess?
