### ISSUE TITLE
[lucre3] Timeline split objects not working

### ISSUE THREAD

**Issue by Sciss** [Sciss/Mellite#16]
The folllowing happens (lucre3):

```
java.lang.AssertionError: assertion failed  at scala.Predef$.assert(Predef.scala:151)   at de.sciss.lucre.bitemp.impl.BiGroupImpl$Impl$changed$$anonfun$7$$anonfun$apply$1.apply(BiGroupImpl.scala:302)     at de.sciss.lucre.bitemp.impl.BiGroupImpl$Impl$changed$$anonfun$7$$anonfun$apply$1.apply(BiGroupImpl.scala:300)     at scala.Option.map(Option.scala:146)   at de.sciss.lucre.bitemp.impl.BiGroupImpl$Impl$changed$$anonfun$7.apply(BiGroupImpl.scala:300)  at de.sciss.lucre.bitemp.impl.BiGroupImpl$Impl$changed$$anonfun$7.apply(BiGroupImpl.scala:296)  at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)     at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)     at scala.collection.immutable.Set$Set1.foreach(Set.scala:79)    at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:252)    at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)  at de.sciss.lucre.bitemp.impl.BiGroupImpl$Impl$changed$.pullUpdate(BiGroupImpl.scala:306)   at de.sciss.lucre.event.Push$Impl.apply(Push.scala:112)     at de.sciss.lucre.event.Push$Impl$$anonfun$2.apply(Push.scala:91)   at de.sciss.lucre.event.Push$Impl$$anonfun$2.apply(Push.scala:89)   at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)     at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)     at scala.collection.immutable.Map$Map3.foreach(Map.scala:161)   at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:252)    at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)  at de.sciss.lucre.event.Push$Impl.pull(Push.scala:92)   at de.sciss.lucre.event.Push$.apply(Push.scala:29)  at de.sciss.lucre.event.impl.Generator$class.fire(Generator.scala:22)   at de.sciss.lucre.expr.impl.VarImpl$changed$.fire(VarImpl.scala:33)     at de.sciss.lucre.expr.impl.VarImpl$class.update(VarImpl.scala:70)  at de.sciss.lucre.expr.package$SpanLikeObj$_Var.update(package.scala:210)   at de.sciss.lucre.expr.package$SpanLikeObj$_Var.update(package.scala:210)   at de.sciss.lucre.swing.edit.EditVar$Impl.perform(EditVar.scala:66)     at de.sciss.lucre.swing.edit.EditVar$.apply(EditVar.scala:41)   at de.sciss.lucre.swing.edit.EditVar$.Expr(EditVar.scala:31)    at de.sciss.mellite.gui.edit.Edits$$anonfun$resize$1.apply(Edits.scala:241)     at de.sciss.mellite.gui.edit.Edits$$anonfun$resize$1.apply(Edits.scala:205)     at scala.Option.flatMap(Option.scala:171)   at de.sciss.mellite.gui.edit.Edits$.resize(Edits.scala:205)     at de.sciss.mellite.gui.impl.timeline.TimelineActions$class.de$sciss$mellite$gui$impl$timeline$TimelineActions$$splitObject(TimelineActions.scala:248)  at de.sciss.mellite.gui.impl.timeline.TimelineActions$$anonfun$splitObjects$1$$anonfun$11.apply(TimelineActions.scala:209)  at de.sciss.mellite.gui.impl.timeline.TimelineActions$$anonfun$splitObjects$1$$anonfun$11.apply(TimelineActions.scala:206)  at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:396)   at scala.collection.Iterator$class.foreach(Iterator.scala:742)  at scala.collection.AbstractIterator.foreach(Iterator.scala:1194)   at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)     at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:183)  at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:45)   at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:308)     at scala.collection.AbstractIterator.to(Iterator.scala:1194)    at scala.collection.TraversableOnce$class.toList(TraversableOnce.scala:292)     at scala.collection.AbstractIterator.toList(Iterator.scala:1194)    at de.sciss.mellite.gui.impl.timeline.TimelineActions$$anonfun$splitObjects$1.apply(TimelineActions.scala:213)  at de.sciss.mellite.gui.impl.timeline.TimelineActions$$anonfun$splitObjects$1.apply(TimelineActions.scala:205)  at scala.Option.flatMap(Option.scala:171)   at de.sciss.mellite.gui.impl.timeline.TimelineActions$class.splitObjects(TimelineActions.scala:205)     at de.sciss.mellite.gui.impl.timeline.TimelineViewImpl$Impl.splitObjects(TimelineViewImpl.scala:332)    at de.sciss.mellite.gui.impl.timeline.TimelineActions$actionSplitObjects$$anonfun$3$$anonfun$apply$5.apply(TimelineActions.scala:87)    at de.sciss.mellite.gui.impl.timeline.TimelineActions$actionSplitObjects$$anonfun$3$$anonfun$apply$5.apply(TimelineActions.scala:87)    at de.sciss.mellite.gui.impl.timeline.TimelineActions$$anonfun$withFilteredSelection$1.apply(TimelineActions.scala:278)     at de.sciss.mellite.gui.impl.timeline.TimelineActions$$anonfun$withFilteredSelection$1.apply(TimelineActions.scala:278)
```

**Comment by Sciss** [comment]
Cannot reproduce, probably outdated
