### ISSUE TITLE
Freesound: don't release cache too early

### ISSUE THREAD

**Issue by Sciss** [Sciss/Mellite#32]
This happens when you press stop while play is still flashing (preview is being downloaded):

```
java.lang.IllegalStateException: Entry for https://www.freesound.org/data/previews/118/118778_1708550-lq.ogg is still being produced
	at de.sciss.filecache.impl.ProducerImpl.releaseImpl(ProducerImpl.scala:270)
	at de.sciss.filecache.impl.ProducerImpl.releaseImpl$(ProducerImpl.scala:267)
	at de.sciss.filecache.impl.TxnProducerImpl.releaseImpl(TxnProducerImpl.scala:21)
	at de.sciss.filecache.impl.TxnProducerImpl.release(TxnProducerImpl.scala:75)
	at de.sciss.filecache.impl.TxnConsumerImpl.release(TxnConsumerImpl.scala:60)
	at de.sciss.freesound.lucre.impl.PreviewsCacheImpl$Impl.release(PreviewsCacheImpl.scala:66)
```

**Comment by Sciss** [comment]
There is more severe cases, where the entire system stops working, perhaps because of broken previews. Sound to demonstrate is 35845. Here we can't get preview playback (transport goes immediately back to stop). Then trying to do anything, we have "Key ... was not in use"
