### ISSUE TITLE
Scheduler bug with adjacent regions?

### ISSUE THREAD

**Issue by Sciss** [Sciss/Mellite#71]
In file `Aneignungen171209[0].zip` at the cut at 0:00:18.459, the RHS is not played when the LHS was scheduled. (Likely in SP)

**Comment by Sciss** [comment]
Likely related:

```
While executing scheduled function 9:
scala.MatchError: null
	at de.sciss.lucre.data.DeterministicSkipOctree$Impl$RangeQuery.findHighestUncritical(DeterministicSkipOctree.scala:1111)
	at de.sciss.lucre.data.DeterministicSkipOctree$Impl$RangeQuery.findNextValue(DeterministicSkipOctree.scala:1132)
	at de.sciss.lucre.data.DeterministicSkipOctree$Impl$RangeQuery.next(DeterministicSkipOctree.scala:1118)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at de.sciss.lucre.data.DeterministicSkipOctree$Impl$RangeQuery.foreach(DeterministicSkipOctree.scala:1045)
	at de.sciss.synth.proc.impl.AuralTimelineBase.playViews(AuralTimelineBase.scala:180)
	at de.sciss.synth.proc.impl.AuralTimelineBase.processEvent(AuralTimelineBase.scala:164)
	at de.sciss.synth.proc.impl.AuralTimelineBase.processEvent$(AuralTimelineBase.scala:145)
	at de.sciss.synth.proc.impl.AuralTimelineImpl$Impl.processEvent(AuralTimelineImpl.scala:61)
	at de.sciss.synth.proc.impl.AuralScheduledBase.eventReached(AuralScheduledBase.scala:327)
	at de.sciss.synth.proc.impl.AuralScheduledBase.$anonfun$scheduleNextEvent$2(AuralScheduledBase.scala:305)
	at de.sciss.synth.proc.impl.AuralScheduledBase.$anonfun$scheduleNextEvent$2$adapted(AuralScheduledBase.scala:304)
	at de.sciss.synth.proc.impl.SchedulerImpl$Impl.$anonfun$eventReached$3(SchedulerImpl.scala:251)
	at de.sciss.synth.proc.impl.SchedulerImpl$Impl.$anonfun$eventReached$3$adapted(SchedulerImpl.scala:248)
	at scala.Option.foreach(Option.scala:257)
	at de.sciss.synth.proc.impl.SchedulerImpl$Impl.$anonfun$eventReached$2(SchedulerImpl.scala:248)
	at scala.runtime.java8.JFunction1$mcVI$sp.apply(JFunction1$mcVI$sp.java:12)
	at scala.collection.immutable.Set$Set1.foreach(Set.scala:95)
	at de.sciss.synth.proc.impl.SchedulerImpl$Impl.$anonfun$eventReached$1(SchedulerImpl.scala:246)
	at de.sciss.synth.proc.impl.SchedulerImpl$Impl.$anonfun$eventReached$1$adapted(SchedulerImpl.scala:244)
	at scala.Option.foreach(Option.scala:257)
	at de.sciss.synth.proc.impl.SchedulerImpl$Impl.eventReached(SchedulerImpl.scala:244)
	at de.sciss.synth.proc.impl.SchedulerImpl$RealtimeImpl$$anon$1.$anonfun$run$2(SchedulerImpl.scala:123)
	at de.sciss.synth.proc.impl.SchedulerImpl$RealtimeImpl$$anon$1.$anonfun$run$2$adapted(SchedulerImpl.scala:122)
	at de.sciss.lucre.stm.impl.DurableImpl$Mixin.$anonfun$step$1(DurableImpl.scala:76)
	at scala.concurrent.stm.ccstm.InTxnImpl.runBlock(InTxnImpl.scala:571)
	at scala.concurrent.stm.ccstm.InTxnImpl.topLevelAttempt(InTxnImpl.scala:527)
	at scala.concurrent.stm.ccstm.InTxnImpl.topLevelAtomicImpl(InTxnImpl.scala:398)
	at scala.concurrent.stm.ccstm.InTxnImpl.atomic(InTxnImpl.scala:259)
	at scala.concurrent.stm.ccstm.CCSTMExecutor.apply(CCSTMExecutor.scala:24)
	at de.sciss.lucre.stm.Txn$.atomic(Txn.scala:109)
	at de.sciss.lucre.stm.impl.DurableImpl$Mixin.step(DurableImpl.scala:75)
	at de.sciss.lucre.stm.impl.DurableImpl$Mixin.step$(DurableImpl.scala:75)
	at de.sciss.synth.proc.impl.DurableImpl$System.step(DurableImpl.scala:41)
	at de.sciss.synth.proc.impl.SchedulerImpl$RealtimeImpl$$anon$1.run(SchedulerImpl.scala:122)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
