### ISSUE TITLE
Consider Java 11

### ISSUE THREAD

**Issue by Sciss** [Sciss/Mellite#97]
In GitLab by @Sciss on Mar 27, 2019, 21:40

This ticket is to collect issues running under JDK 11.

# Submin / WebLaF

```
[AWT-EventQueue-0] ERROR com.alee.utils.ProprietaryUtils - java.lang.NoSuchFieldException: AA_TEXT_PROPERTY_KEY
java.lang.NoSuchFieldException: AA_TEXT_PROPERTY_KEY
	at java.base/java.lang.Class.getField(Class.java:2000)
	at com.alee.utils.ReflectUtils.getStaticFieldValue(ReflectUtils.java:384)
	at com.alee.utils.ProprietaryUtils.setupUIDefaults(ProprietaryUtils.java:103)
	at com.alee.laf.WebLookAndFeel.initComponentDefaults(WebLookAndFeel.java:546)
	at java.desktop/javax.swing.plaf.basic.BasicLookAndFeel.getDefaults(BasicLookAndFeel.java:150)
	at java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:587)
	at java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:633)
	at com.alee.utils.LafUtils.setupLookAndFeelSafely(LafUtils.java:876)
```

(this is harmless)

```
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: com/sun/java/swing/plaf/windows/WindowsLookAndFeel
	at de.sciss.submin.SubminStyledLabelPainter.paintStyledTextImpl(SubminStyledLabelPainter.java:149)
	at de.sciss.submin.SubminStyledLabelPainter.paintStyledText(SubminStyledLabelPainter.java:84)
	at de.sciss.submin.SubminStyledLabelPainter.paintEnabledText(SubminStyledLabelPainter.java:60)
	at de.sciss.submin.SubminStyledLabelPainter.paintEnabledText(SubminStyledLabelPainter.java:36)
	at com.alee.laf.label.AbstractLabelPainter.paintPlainText(AbstractLabelPainter.java:252)
	at com.alee.laf.label.AbstractLabelPainter.paintText(AbstractLabelPainter.java:209)
	at com.alee.laf.label.AbstractLabelPainter.paintContent(AbstractLabelPainter.java:153)
	at com.alee.laf.label.AbstractLabelPainter.paintContent(AbstractLabelPainter.java:42)
	at com.alee.painter.decoration.AbstractDecorationPainter.paint(AbstractDecorationPainter.java:706)
	at com.alee.extended.label.WebStyledLabelUI.paint(WebStyledLabelUI.java:192)
	at java.desktop/javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
	at java.desktop/javax.swing.JComponent.paintComponent(JComponent.java:797)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1074)
	at java.desktop/javax.swing.CellRendererPane.paintComponent(CellRendererPane.java:165)
	at com.alee.laf.combobox.ComboBoxPainter.paintCurrentValue(ComboBoxPainter.java:197)
```

This is __serious__.

# JavaFX

This is a drama. So JDK 8 is supported on _many_ Linux'es through package `openjfx` (e.g. Debian), but this is broken or incomplete on Raspbian and perhaps also some Ubuntu distributions. Then JDK 11 does not feature any corresponding JavaFX package. Instead we can depend on Maven artifacts but need to select OS classifiers. Like so

```scala
lazy val jfxClassifer = System.getProperty("os.name") match {
  case n if n.startsWith("Linux")   => "linux"
  case n if n.startsWith("Mac")     => "mac"
  case n if n.startsWith("Windows") => "win"
  case _ => throw new Exception("Unknown platform!")
}

    libraryDependencies ++= Seq(
      "org.openjfx" % "javafx-swing"    % "11.0.2" classifier jfxClassifer,
      "org.openjfx" % "javafx-graphics" % "11.0.2" classifier jfxClassifer,
    ),
```

**Comment by Sciss** [comment]
In GitLab by @Sciss on Mar 27, 2019, 21:41

changed the description

**Comment by Sciss** [comment]
In GitLab by @Sciss on Mar 27, 2019, 22:30

For packaging with jlink: https://stackoverflow.com/questions/47593409/create-java-runtime-image-on-one-platform-for-another-using-jlink

**Comment by Sciss** [comment]
In GitLab by @Sciss on Sep 1, 2019, 15:54

jlink test: https://git.iem.at/sciss/Impulse/tree/jlink-test

Now we only need a way to run this on all platforms (linux x86, raspbian / arm, windows, mac)

**Comment by Sciss** [comment]
In GitLab by @Sciss on Oct 17, 2019, 02:04

closed
